#pragma once

#ifdef __APPLE__

#include <Accelerate/Accelerate.h>

typedef int lapack_int;
typedef float lapack_real;
typedef double lapack_dreal;


#define LAPACK_cbdsqr cbdsqr_
#define LAPACK_cgbbrd cgbbrd_
#define LAPACK_cgbcon cgbcon_
#define LAPACK_cgbequ cgbequ_
#define LAPACK_cgbequb cgbequb_
#define LAPACK_cgbrfs cgbrfs_
#define LAPACK_cgbsv cgbsv_
#define LAPACK_cgbsvx cgbsvx_
#define LAPACK_cgbtf2 cgbtf2_
#define LAPACK_cgbtrf cgbtrf_
#define LAPACK_cgbtrs cgbtrs_
#define LAPACK_cgebak cgebak_
#define LAPACK_cgebal cgebal_
#define LAPACK_cgebd2 cgebd2_
#define LAPACK_cgebrd cgebrd_
#define LAPACK_cgecon cgecon_
#define LAPACK_cgeequ cgeequ_
#define LAPACK_cgeequb cgeequb_
#define LAPACK_cgees cgees_
#define LAPACK_cgeesx cgeesx_
#define LAPACK_cgeev cgeev_
#define LAPACK_cgeevx cgeevx_
#define LAPACK_cgegs cgegs_
#define LAPACK_cgegv cgegv_
#define LAPACK_cgehd2 cgehd2_
#define LAPACK_cgehrd cgehrd_
#define LAPACK_cgelq2 cgelq2_
#define LAPACK_cgelqf cgelqf_
#define LAPACK_cgels cgels_
#define LAPACK_cgelsd cgelsd_
#define LAPACK_cgelss cgelss_
#define LAPACK_cgelsx cgelsx_
#define LAPACK_cgelsy cgelsy_
#define LAPACK_cgeql2 cgeql2_
#define LAPACK_cgeqlf cgeqlf_
#define LAPACK_cgeqp3 cgeqp3_
#define LAPACK_cgeqpf cgeqpf_
#define LAPACK_cgeqr2 cgeqr2_
#define LAPACK_cgeqrf cgeqrf_
#define LAPACK_cgerfs cgerfs_
#define LAPACK_cgerq2 cgerq2_
#define LAPACK_cgerqf cgerqf_
#define LAPACK_cgesc2 cgesc2_
#define LAPACK_cgesdd cgesdd_
#define LAPACK_cgesv cgesv_
#define LAPACK_cgesvd cgesvd_
#define LAPACK_cgesvx cgesvx_
#define LAPACK_cgetc2 cgetc2_
#define LAPACK_cgetf2 cgetf2_
#define LAPACK_cgetrf cgetrf_
#define LAPACK_cgetri cgetri_
#define LAPACK_cgetrs cgetrs_
#define LAPACK_cggbak cggbak_
#define LAPACK_cggbal cggbal_
#define LAPACK_cgges cgges_
#define LAPACK_cggesx cggesx_
#define LAPACK_cggev cggev_
#define LAPACK_cggevx cggevx_
#define LAPACK_cggglm cggglm_
#define LAPACK_cgghrd cgghrd_
#define LAPACK_cgglse cgglse_
#define LAPACK_cggqrf cggqrf_
#define LAPACK_cggrqf cggrqf_
#define LAPACK_cggsvd cggsvd_
#define LAPACK_cggsvp cggsvp_
#define LAPACK_cgtcon cgtcon_
#define LAPACK_cgtrfs cgtrfs_
#define LAPACK_cgtsv cgtsv_
#define LAPACK_cgtsvx cgtsvx_
#define LAPACK_cgttrf cgttrf_
#define LAPACK_cgttrs cgttrs_
#define LAPACK_cgtts2 cgtts2_
#define LAPACK_chbev chbev_
#define LAPACK_chbevd chbevd_
#define LAPACK_chbevx chbevx_
#define LAPACK_chbgst chbgst_
#define LAPACK_chbgv chbgv_
#define LAPACK_chbgvd chbgvd_
#define LAPACK_chbgvx chbgvx_
#define LAPACK_chbtrd chbtrd_
#define LAPACK_checon checon_
#define LAPACK_cheequb cheequb_
#define LAPACK_cheev cheev_
#define LAPACK_cheevd cheevd_
#define LAPACK_cheevr cheevr_
#define LAPACK_cheevx cheevx_
#define LAPACK_chegs2 chegs2_
#define LAPACK_chegst chegst_
#define LAPACK_chegv chegv_
#define LAPACK_chegvd chegvd_
#define LAPACK_chegvx chegvx_
#define LAPACK_cherfs cherfs_
#define LAPACK_chesv chesv_
#define LAPACK_chesvx chesvx_
#define LAPACK_chetd2 chetd2_
#define LAPACK_chetf2 chetf2_
#define LAPACK_chetrd chetrd_
#define LAPACK_chetrf chetrf_
#define LAPACK_chetri chetri_
#define LAPACK_chetrs chetrs_
#define LAPACK_chfrk chfrk_
#define LAPACK_chgeqz chgeqz_
#define LAPACK_chla_transtype_ chla_transtype__
#define LAPACK_chpcon chpcon_
#define LAPACK_chpev chpev_
#define LAPACK_chpevd chpevd_
#define LAPACK_chpevx chpevx_
#define LAPACK_chpgst chpgst_
#define LAPACK_chpgv chpgv_
#define LAPACK_chpgvd chpgvd_
#define LAPACK_chpgvx chpgvx_
#define LAPACK_chprfs chprfs_
#define LAPACK_chpsv chpsv_
#define LAPACK_chpsvx chpsvx_
#define LAPACK_chptrd chptrd_
#define LAPACK_chptrf chptrf_
#define LAPACK_chptri chptri_
#define LAPACK_chptrs chptrs_
#define LAPACK_chsein chsein_
#define LAPACK_chseqr chseqr_
#define LAPACK_clabrd clabrd_
#define LAPACK_clacgv clacgv_
#define LAPACK_clacn2 clacn2_
#define LAPACK_clacon clacon_
#define LAPACK_clacp2 clacp2_
#define LAPACK_clacpy clacpy_
#define LAPACK_clacrm clacrm_
#define LAPACK_clacrt clacrt_
#define LAPACK_cladiv cladiv_
#define LAPACK_claed0 claed0_
#define LAPACK_claed7 claed7_
#define LAPACK_claed8 claed8_
#define LAPACK_claein claein_
#define LAPACK_claesy claesy_
#define LAPACK_claev2 claev2_
#define LAPACK_clag2z clag2z_
#define LAPACK_clags2 clags2_
#define LAPACK_clagtm clagtm_
#define LAPACK_clahef clahef_
#define LAPACK_clahqr clahqr_
#define LAPACK_clahr2 clahr2_
#define LAPACK_clahrd clahrd_
#define LAPACK_claic1 claic1_
#define LAPACK_clals0 clals0_
#define LAPACK_clalsa clalsa_
#define LAPACK_clalsd clalsd_
#define LAPACK_clangb clangb_
#define LAPACK_clange clange_
#define LAPACK_clangt clangt_
#define LAPACK_clanhb clanhb_
#define LAPACK_clanhe clanhe_
#define LAPACK_clanhf clanhf_
#define LAPACK_clanhp clanhp_
#define LAPACK_clanhs clanhs_
#define LAPACK_clanht clanht_
#define LAPACK_clansb clansb_
#define LAPACK_clansp clansp_
#define LAPACK_clansy clansy_
#define LAPACK_clantb clantb_
#define LAPACK_clantp clantp_
#define LAPACK_clantr clantr_
#define LAPACK_clapll clapll_
#define LAPACK_clapmt clapmt_
#define LAPACK_claqgb claqgb_
#define LAPACK_claqge claqge_
#define LAPACK_claqhb claqhb_
#define LAPACK_claqhe claqhe_
#define LAPACK_claqhp claqhp_
#define LAPACK_claqp2 claqp2_
#define LAPACK_claqps claqps_
#define LAPACK_claqr0 claqr0_
#define LAPACK_claqr1 claqr1_
#define LAPACK_claqr2 claqr2_
#define LAPACK_claqr3 claqr3_
#define LAPACK_claqr4 claqr4_
#define LAPACK_claqr5 claqr5_
#define LAPACK_claqsb claqsb_
#define LAPACK_claqsp claqsp_
#define LAPACK_claqsy claqsy_
#define LAPACK_clar1v clar1v_
#define LAPACK_clar2v clar2v_
#define LAPACK_clarcm clarcm_
#define LAPACK_clarf clarf_
#define LAPACK_clarfb clarfb_
#define LAPACK_clarfg clarfg_
#define LAPACK_clarfp clarfp_
#define LAPACK_clarft clarft_
#define LAPACK_clarfx clarfx_
#define LAPACK_clargv clargv_
#define LAPACK_clarnv clarnv_
#define LAPACK_clarrv clarrv_
#define LAPACK_clarscl2 clarscl2_
#define LAPACK_clartg clartg_
#define LAPACK_clartv clartv_
#define LAPACK_clarz clarz_
#define LAPACK_clarzb clarzb_
#define LAPACK_clarzt clarzt_
#define LAPACK_clascl clascl_
#define LAPACK_clascl2 clascl2_
#define LAPACK_claset claset_
#define LAPACK_clasr clasr_
#define LAPACK_classq classq_
#define LAPACK_claswp claswp_
#define LAPACK_clasyf clasyf_
#define LAPACK_clatbs clatbs_
#define LAPACK_clatdf clatdf_
#define LAPACK_clatps clatps_
#define LAPACK_clatrd clatrd_
#define LAPACK_clatrs clatrs_
#define LAPACK_clatrz clatrz_
#define LAPACK_clatzm clatzm_
#define LAPACK_clauu2 clauu2_
#define LAPACK_clauum clauum_
#define LAPACK_cpbcon cpbcon_
#define LAPACK_cpbequ cpbequ_
#define LAPACK_cpbrfs cpbrfs_
#define LAPACK_cpbstf cpbstf_
#define LAPACK_cpbsv cpbsv_
#define LAPACK_cpbsvx cpbsvx_
#define LAPACK_cpbtf2 cpbtf2_
#define LAPACK_cpbtrf cpbtrf_
#define LAPACK_cpbtrs cpbtrs_
#define LAPACK_cpftrf cpftrf_
#define LAPACK_cpftri cpftri_
#define LAPACK_cpftrs cpftrs_
#define LAPACK_cpocon cpocon_
#define LAPACK_cpoequ cpoequ_
#define LAPACK_cpoequb cpoequb_
#define LAPACK_cporfs cporfs_
#define LAPACK_cposv cposv_
#define LAPACK_cposvx cposvx_
#define LAPACK_cpotf2 cpotf2_
#define LAPACK_cpotrf cpotrf_
#define LAPACK_cpotri cpotri_
#define LAPACK_cpotrs cpotrs_
#define LAPACK_cppcon cppcon_
#define LAPACK_cppequ cppequ_
#define LAPACK_cpprfs cpprfs_
#define LAPACK_cppsv cppsv_
#define LAPACK_cppsvx cppsvx_
#define LAPACK_cpptrf cpptrf_
#define LAPACK_cpptri cpptri_
#define LAPACK_cpptrs cpptrs_
#define LAPACK_cpstf2 cpstf2_
#define LAPACK_cpstrf cpstrf_
#define LAPACK_cptcon cptcon_
#define LAPACK_cpteqr cpteqr_
#define LAPACK_cptrfs cptrfs_
#define LAPACK_cptsv cptsv_
#define LAPACK_cptsvx cptsvx_
#define LAPACK_cpttrf cpttrf_
#define LAPACK_cpttrs cpttrs_
#define LAPACK_cptts2 cptts2_
#define LAPACK_crot crot_
#define LAPACK_cspcon cspcon_
#define LAPACK_cspmv cspmv_
#define LAPACK_cspr cspr_
#define LAPACK_csprfs csprfs_
#define LAPACK_cspsv cspsv_
#define LAPACK_cspsvx cspsvx_
#define LAPACK_csptrf csptrf_
#define LAPACK_csptri csptri_
#define LAPACK_csptrs csptrs_
#define LAPACK_csrscl csrscl_
#define LAPACK_cstedc cstedc_
#define LAPACK_cstegr cstegr_
#define LAPACK_cstein cstein_
#define LAPACK_cstemr cstemr_
#define LAPACK_csteqr csteqr_
#define LAPACK_csycon csycon_
#define LAPACK_csyequb csyequb_
#define LAPACK_csymv csymv_
#define LAPACK_csyr csyr_
#define LAPACK_csyrfs csyrfs_
#define LAPACK_csysv csysv_
#define LAPACK_csysvx csysvx_
#define LAPACK_csytf2 csytf2_
#define LAPACK_csytrf csytrf_
#define LAPACK_csytri csytri_
#define LAPACK_csytrs csytrs_
#define LAPACK_ctbcon ctbcon_
#define LAPACK_ctbrfs ctbrfs_
#define LAPACK_ctbtrs ctbtrs_
#define LAPACK_ctfsm ctfsm_
#define LAPACK_ctftri ctftri_
#define LAPACK_ctfttp ctfttp_
#define LAPACK_ctfttr ctfttr_
#define LAPACK_ctgevc ctgevc_
#define LAPACK_ctgex2 ctgex2_
#define LAPACK_ctgexc ctgexc_
#define LAPACK_ctgsen ctgsen_
#define LAPACK_ctgsja ctgsja_
#define LAPACK_ctgsna ctgsna_
#define LAPACK_ctgsy2 ctgsy2_
#define LAPACK_ctgsyl ctgsyl_
#define LAPACK_ctpcon ctpcon_
#define LAPACK_ctprfs ctprfs_
#define LAPACK_ctptri ctptri_
#define LAPACK_ctptrs ctptrs_
#define LAPACK_ctpttf ctpttf_
#define LAPACK_ctpttr ctpttr_
#define LAPACK_ctrcon ctrcon_
#define LAPACK_ctrevc ctrevc_
#define LAPACK_ctrexc ctrexc_
#define LAPACK_ctrrfs ctrrfs_
#define LAPACK_ctrsen ctrsen_
#define LAPACK_ctrsna ctrsna_
#define LAPACK_ctrsyl ctrsyl_
#define LAPACK_ctrti2 ctrti2_
#define LAPACK_ctrtri ctrtri_
#define LAPACK_ctrtrs ctrtrs_
#define LAPACK_ctrttf ctrttf_
#define LAPACK_ctrttp ctrttp_
#define LAPACK_ctzrqf ctzrqf_
#define LAPACK_ctzrzf ctzrzf_
#define LAPACK_cung2l cung2l_
#define LAPACK_cung2r cung2r_
#define LAPACK_cungbr cungbr_
#define LAPACK_cunghr cunghr_
#define LAPACK_cungl2 cungl2_
#define LAPACK_cunglq cunglq_
#define LAPACK_cungql cungql_
#define LAPACK_cungqr cungqr_
#define LAPACK_cungr2 cungr2_
#define LAPACK_cungrq cungrq_
#define LAPACK_cungtr cungtr_
#define LAPACK_cunm2l cunm2l_
#define LAPACK_cunm2r cunm2r_
#define LAPACK_cunmbr cunmbr_
#define LAPACK_cunmhr cunmhr_
#define LAPACK_cunml2 cunml2_
#define LAPACK_cunmlq cunmlq_
#define LAPACK_cunmql cunmql_
#define LAPACK_cunmqr cunmqr_
#define LAPACK_cunmr2 cunmr2_
#define LAPACK_cunmr3 cunmr3_
#define LAPACK_cunmrq cunmrq_
#define LAPACK_cunmrz cunmrz_
#define LAPACK_cunmtr cunmtr_
#define LAPACK_cupgtr cupgtr_
#define LAPACK_cupmtr cupmtr_
#define LAPACK_dbdsdc dbdsdc_
#define LAPACK_dbdsqr dbdsqr_
#define LAPACK_ddisna ddisna_
#define LAPACK_dgbbrd dgbbrd_
#define LAPACK_dgbcon dgbcon_
#define LAPACK_dgbequ dgbequ_
#define LAPACK_dgbequb dgbequb_
#define LAPACK_dgbrfs dgbrfs_
#define LAPACK_dgbsv dgbsv_
#define LAPACK_dgbsvx dgbsvx_
#define LAPACK_dgbtf2 dgbtf2_
#define LAPACK_dgbtrf dgbtrf_
#define LAPACK_dgbtrs dgbtrs_
#define LAPACK_dgebak dgebak_
#define LAPACK_dgebal dgebal_
#define LAPACK_dgebd2 dgebd2_
#define LAPACK_dgebrd dgebrd_
#define LAPACK_dgecon dgecon_
#define LAPACK_dgeequ dgeequ_
#define LAPACK_dgeequb dgeequb_
#define LAPACK_dgees dgees_
#define LAPACK_dgeesx dgeesx_
#define LAPACK_dgeev dgeev_
#define LAPACK_dgeevx dgeevx_
#define LAPACK_dgegs dgegs_
#define LAPACK_dgegv dgegv_
#define LAPACK_dgehd2 dgehd2_
#define LAPACK_dgehrd dgehrd_
#define LAPACK_dgejsv dgejsv_
#define LAPACK_dgelq2 dgelq2_
#define LAPACK_dgelqf dgelqf_
#define LAPACK_dgels dgels_
#define LAPACK_dgelsd dgelsd_
#define LAPACK_dgelss dgelss_
#define LAPACK_dgelsx dgelsx_
#define LAPACK_dgelsy dgelsy_
#define LAPACK_dgeql2 dgeql2_
#define LAPACK_dgeqlf dgeqlf_
#define LAPACK_dgeqp3 dgeqp3_
#define LAPACK_dgeqpf dgeqpf_
#define LAPACK_dgeqr2 dgeqr2_
#define LAPACK_dgeqrf dgeqrf_
#define LAPACK_dgerfs dgerfs_
#define LAPACK_dgerq2 dgerq2_
#define LAPACK_dgerqf dgerqf_
#define LAPACK_dgesc2 dgesc2_
#define LAPACK_dgesdd dgesdd_
#define LAPACK_dgesv dgesv_
#define LAPACK_dgesvd dgesvd_
#define LAPACK_dgesvj dgesvj_
#define LAPACK_dgesvx dgesvx_
#define LAPACK_dgetc2 dgetc2_
#define LAPACK_dgetf2 dgetf2_
#define LAPACK_dgetrf dgetrf_
#define LAPACK_dgetri dgetri_
#define LAPACK_dgetrs dgetrs_
#define LAPACK_dggbak dggbak_
#define LAPACK_dggbal dggbal_
#define LAPACK_dgges dgges_
#define LAPACK_dggesx dggesx_
#define LAPACK_dggev dggev_
#define LAPACK_dggevx dggevx_
#define LAPACK_dggglm dggglm_
#define LAPACK_dgghrd dgghrd_
#define LAPACK_dgglse dgglse_
#define LAPACK_dggqrf dggqrf_
#define LAPACK_dggrqf dggrqf_
#define LAPACK_dggsvd dggsvd_
#define LAPACK_dggsvp dggsvp_
#define LAPACK_dgsvj0 dgsvj0_
#define LAPACK_dgsvj1 dgsvj1_
#define LAPACK_dgtcon dgtcon_
#define LAPACK_dgtrfs dgtrfs_
#define LAPACK_dgtsv dgtsv_
#define LAPACK_dgtsvx dgtsvx_
#define LAPACK_dgttrf dgttrf_
#define LAPACK_dgttrs dgttrs_
#define LAPACK_dgtts2 dgtts2_
#define LAPACK_dhgeqz dhgeqz_
#define LAPACK_dhsein dhsein_
#define LAPACK_dhseqr dhseqr_
#define LAPACK_disnan disnan_
#define LAPACK_dlabad dlabad_
#define LAPACK_dlabrd dlabrd_
#define LAPACK_dlacn2 dlacn2_
#define LAPACK_dlacon dlacon_
#define LAPACK_dlacpy dlacpy_
#define LAPACK_dladiv dladiv_
#define LAPACK_dlae2 dlae2_
#define LAPACK_dlaebz dlaebz_
#define LAPACK_dlaed0 dlaed0_
#define LAPACK_dlaed1 dlaed1_
#define LAPACK_dlaed2 dlaed2_
#define LAPACK_dlaed3 dlaed3_
#define LAPACK_dlaed4 dlaed4_
#define LAPACK_dlaed5 dlaed5_
#define LAPACK_dlaed6 dlaed6_
#define LAPACK_dlaed7 dlaed7_
#define LAPACK_dlaed8 dlaed8_
#define LAPACK_dlaed9 dlaed9_
#define LAPACK_dlaeda dlaeda_
#define LAPACK_dlaein dlaein_
#define LAPACK_dlaev2 dlaev2_
#define LAPACK_dlaexc dlaexc_
#define LAPACK_dlag2 dlag2_
#define LAPACK_dlag2s dlag2s_
#define LAPACK_dlags2 dlags2_
#define LAPACK_dlagtf dlagtf_
#define LAPACK_dlagtm dlagtm_
#define LAPACK_dlagts dlagts_
#define LAPACK_dlagv2 dlagv2_
#define LAPACK_dlahqr dlahqr_
#define LAPACK_dlahr2 dlahr2_
#define LAPACK_dlahrd dlahrd_
#define LAPACK_dlaic1 dlaic1_
#define LAPACK_dlaisnan dlaisnan_
#define LAPACK_dlaln2 dlaln2_
#define LAPACK_dlals0 dlals0_
#define LAPACK_dlalsa dlalsa_
#define LAPACK_dlalsd dlalsd_
#define LAPACK_dlamrg dlamrg_
#define LAPACK_dlaneg dlaneg_
#define LAPACK_dlangb dlangb_
#define LAPACK_dlange dlange_
#define LAPACK_dlangt dlangt_
#define LAPACK_dlanhs dlanhs_
#define LAPACK_dlansb dlansb_
#define LAPACK_dlansf dlansf_
#define LAPACK_dlansp dlansp_
#define LAPACK_dlanst dlanst_
#define LAPACK_dlansy dlansy_
#define LAPACK_dlantb dlantb_
#define LAPACK_dlantp dlantp_
#define LAPACK_dlantr dlantr_
#define LAPACK_dlanv2 dlanv2_
#define LAPACK_dlapll dlapll_
#define LAPACK_dlapmt dlapmt_
#define LAPACK_dlapy2 dlapy2_
#define LAPACK_dlapy3 dlapy3_
#define LAPACK_dlaqgb dlaqgb_
#define LAPACK_dlaqge dlaqge_
#define LAPACK_dlaqp2 dlaqp2_
#define LAPACK_dlaqps dlaqps_
#define LAPACK_dlaqr0 dlaqr0_
#define LAPACK_dlaqr1 dlaqr1_
#define LAPACK_dlaqr2 dlaqr2_
#define LAPACK_dlaqr3 dlaqr3_
#define LAPACK_dlaqr4 dlaqr4_
#define LAPACK_dlaqr5 dlaqr5_
#define LAPACK_dlaqsb dlaqsb_
#define LAPACK_dlaqsp dlaqsp_
#define LAPACK_dlaqsy dlaqsy_
#define LAPACK_dlaqtr dlaqtr_
#define LAPACK_dlar1v dlar1v_
#define LAPACK_dlar2v dlar2v_
#define LAPACK_dlarf dlarf_
#define LAPACK_dlarfb dlarfb_
#define LAPACK_dlarfg dlarfg_
#define LAPACK_dlarfp dlarfp_
#define LAPACK_dlarft dlarft_
#define LAPACK_dlarfx dlarfx_
#define LAPACK_dlargv dlargv_
#define LAPACK_dlarnv dlarnv_
#define LAPACK_dlarra dlarra_
#define LAPACK_dlarrb dlarrb_
#define LAPACK_dlarrc dlarrc_
#define LAPACK_dlarrd dlarrd_
#define LAPACK_dlarre dlarre_
#define LAPACK_dlarrf dlarrf_
#define LAPACK_dlarrj dlarrj_
#define LAPACK_dlarrk dlarrk_
#define LAPACK_dlarrr dlarrr_
#define LAPACK_dlarrv dlarrv_
#define LAPACK_dlarscl2 dlarscl2_
#define LAPACK_dlartg dlartg_
#define LAPACK_dlartv dlartv_
#define LAPACK_dlaruv dlaruv_
#define LAPACK_dlarz dlarz_
#define LAPACK_dlarzb dlarzb_
#define LAPACK_dlarzt dlarzt_
#define LAPACK_dlas2 dlas2_
#define LAPACK_dlascl dlascl_
#define LAPACK_dlascl2 dlascl2_
#define LAPACK_dlasd0 dlasd0_
#define LAPACK_dlasd1 dlasd1_
#define LAPACK_dlasd2 dlasd2_
#define LAPACK_dlasd3 dlasd3_
#define LAPACK_dlasd4 dlasd4_
#define LAPACK_dlasd5 dlasd5_
#define LAPACK_dlasd6 dlasd6_
#define LAPACK_dlasd7 dlasd7_
#define LAPACK_dlasd8 dlasd8_
#define LAPACK_dlasda dlasda_
#define LAPACK_dlasdq dlasdq_
#define LAPACK_dlasdt dlasdt_
#define LAPACK_dlaset dlaset_
#define LAPACK_dlasq1 dlasq1_
#define LAPACK_dlasq2 dlasq2_
#define LAPACK_dlasq3 dlasq3_
#define LAPACK_dlasq4 dlasq4_
#define LAPACK_dlasq5 dlasq5_
#define LAPACK_dlasq6 dlasq6_
#define LAPACK_dlasr dlasr_
#define LAPACK_dlasrt dlasrt_
#define LAPACK_dlassq dlassq_
#define LAPACK_dlasv2 dlasv2_
#define LAPACK_dlaswp dlaswp_
#define LAPACK_dlasy2 dlasy2_
#define LAPACK_dlasyf dlasyf_
#define LAPACK_dlat2s dlat2s_
#define LAPACK_dlatbs dlatbs_
#define LAPACK_dlatdf dlatdf_
#define LAPACK_dlatps dlatps_
#define LAPACK_dlatrd dlatrd_
#define LAPACK_dlatrs dlatrs_
#define LAPACK_dlatrz dlatrz_
#define LAPACK_dlatzm dlatzm_
#define LAPACK_dlauu2 dlauu2_
#define LAPACK_dlauum dlauum_
#define LAPACK_dopgtr dopgtr_
#define LAPACK_dopmtr dopmtr_
#define LAPACK_dorg2l dorg2l_
#define LAPACK_dorg2r dorg2r_
#define LAPACK_dorgbr dorgbr_
#define LAPACK_dorghr dorghr_
#define LAPACK_dorgl2 dorgl2_
#define LAPACK_dorglq dorglq_
#define LAPACK_dorgql dorgql_
#define LAPACK_dorgqr dorgqr_
#define LAPACK_dorgr2 dorgr2_
#define LAPACK_dorgrq dorgrq_
#define LAPACK_dorgtr dorgtr_
#define LAPACK_dorm2l dorm2l_
#define LAPACK_dorm2r dorm2r_
#define LAPACK_dormbr dormbr_
#define LAPACK_dormhr dormhr_
#define LAPACK_dorml2 dorml2_
#define LAPACK_dormlq dormlq_
#define LAPACK_dormql dormql_
#define LAPACK_dormqr dormqr_
#define LAPACK_dormr2 dormr2_
#define LAPACK_dormr3 dormr3_
#define LAPACK_dormrq dormrq_
#define LAPACK_dormrz dormrz_
#define LAPACK_dormtr dormtr_
#define LAPACK_dpbcon dpbcon_
#define LAPACK_dpbequ dpbequ_
#define LAPACK_dpbrfs dpbrfs_
#define LAPACK_dpbstf dpbstf_
#define LAPACK_dpbsv dpbsv_
#define LAPACK_dpbsvx dpbsvx_
#define LAPACK_dpbtf2 dpbtf2_
#define LAPACK_dpbtrf dpbtrf_
#define LAPACK_dpbtrs dpbtrs_
#define LAPACK_dpftrf dpftrf_
#define LAPACK_dpftri dpftri_
#define LAPACK_dpftrs dpftrs_
#define LAPACK_dpocon dpocon_
#define LAPACK_dpoequ dpoequ_
#define LAPACK_dpoequb dpoequb_
#define LAPACK_dporfs dporfs_
#define LAPACK_dposv dposv_
#define LAPACK_dposvx dposvx_
#define LAPACK_dpotf2 dpotf2_
#define LAPACK_dpotrf dpotrf_
#define LAPACK_dpotri dpotri_
#define LAPACK_dpotrs dpotrs_
#define LAPACK_dppcon dppcon_
#define LAPACK_dppequ dppequ_
#define LAPACK_dpprfs dpprfs_
#define LAPACK_dppsv dppsv_
#define LAPACK_dppsvx dppsvx_
#define LAPACK_dpptrf dpptrf_
#define LAPACK_dpptri dpptri_
#define LAPACK_dpptrs dpptrs_
#define LAPACK_dpstf2 dpstf2_
#define LAPACK_dpstrf dpstrf_
#define LAPACK_dptcon dptcon_
#define LAPACK_dpteqr dpteqr_
#define LAPACK_dptrfs dptrfs_
#define LAPACK_dptsv dptsv_
#define LAPACK_dptsvx dptsvx_
#define LAPACK_dpttrf dpttrf_
#define LAPACK_dpttrs dpttrs_
#define LAPACK_dptts2 dptts2_
#define LAPACK_drscl drscl_
#define LAPACK_dsbev dsbev_
#define LAPACK_dsbevd dsbevd_
#define LAPACK_dsbevx dsbevx_
#define LAPACK_dsbgst dsbgst_
#define LAPACK_dsbgv dsbgv_
#define LAPACK_dsbgvd dsbgvd_
#define LAPACK_dsbgvx dsbgvx_
#define LAPACK_dsbtrd dsbtrd_
#define LAPACK_dsfrk dsfrk_
#define LAPACK_dsgesv dsgesv_
#define LAPACK_dspcon dspcon_
#define LAPACK_dspev dspev_
#define LAPACK_dspevd dspevd_
#define LAPACK_dspevx dspevx_
#define LAPACK_dspgst dspgst_
#define LAPACK_dspgv dspgv_
#define LAPACK_dspgvd dspgvd_
#define LAPACK_dspgvx dspgvx_
#define LAPACK_dsposv dsposv_
#define LAPACK_dsprfs dsprfs_
#define LAPACK_dspsv dspsv_
#define LAPACK_dspsvx dspsvx_
#define LAPACK_dsptrd dsptrd_
#define LAPACK_dsptrf dsptrf_
#define LAPACK_dsptri dsptri_
#define LAPACK_dsptrs dsptrs_
#define LAPACK_dstebz dstebz_
#define LAPACK_dstedc dstedc_
#define LAPACK_dstegr dstegr_
#define LAPACK_dstein dstein_
#define LAPACK_dstemr dstemr_
#define LAPACK_dsteqr dsteqr_
#define LAPACK_dsterf dsterf_
#define LAPACK_dstev dstev_
#define LAPACK_dstevd dstevd_
#define LAPACK_dstevr dstevr_
#define LAPACK_dstevx dstevx_
#define LAPACK_dsycon dsycon_
#define LAPACK_dsyequb dsyequb_
#define LAPACK_dsyev dsyev_
#define LAPACK_dsyevd dsyevd_
#define LAPACK_dsyevr dsyevr_
#define LAPACK_dsyevx dsyevx_
#define LAPACK_dsygs2 dsygs2_
#define LAPACK_dsygst dsygst_
#define LAPACK_dsygv dsygv_
#define LAPACK_dsygvd dsygvd_
#define LAPACK_dsygvx dsygvx_
#define LAPACK_dsyrfs dsyrfs_
#define LAPACK_dsysv dsysv_
#define LAPACK_dsysvx dsysvx_
#define LAPACK_dsytd2 dsytd2_
#define LAPACK_dsytf2 dsytf2_
#define LAPACK_dsytrd dsytrd_
#define LAPACK_dsytrf dsytrf_
#define LAPACK_dsytri dsytri_
#define LAPACK_dsytrs dsytrs_
#define LAPACK_dtbcon dtbcon_
#define LAPACK_dtbrfs dtbrfs_
#define LAPACK_dtbtrs dtbtrs_
#define LAPACK_dtfsm dtfsm_
#define LAPACK_dtftri dtftri_
#define LAPACK_dtfttp dtfttp_
#define LAPACK_dtfttr dtfttr_
#define LAPACK_dtgevc dtgevc_
#define LAPACK_dtgex2 dtgex2_
#define LAPACK_dtgexc dtgexc_
#define LAPACK_dtgsen dtgsen_
#define LAPACK_dtgsja dtgsja_
#define LAPACK_dtgsna dtgsna_
#define LAPACK_dtgsy2 dtgsy2_
#define LAPACK_dtgsyl dtgsyl_
#define LAPACK_dtpcon dtpcon_
#define LAPACK_dtprfs dtprfs_
#define LAPACK_dtptri dtptri_
#define LAPACK_dtptrs dtptrs_
#define LAPACK_dtpttf dtpttf_
#define LAPACK_dtpttr dtpttr_
#define LAPACK_dtrcon dtrcon_
#define LAPACK_dtrevc dtrevc_
#define LAPACK_dtrexc dtrexc_
#define LAPACK_dtrrfs dtrrfs_
#define LAPACK_dtrsen dtrsen_
#define LAPACK_dtrsna dtrsna_
#define LAPACK_dtrsyl dtrsyl_
#define LAPACK_dtrti2 dtrti2_
#define LAPACK_dtrtri dtrtri_
#define LAPACK_dtrtrs dtrtrs_
#define LAPACK_dtrttf dtrttf_
#define LAPACK_dtrttp dtrttp_
#define LAPACK_dtzrqf dtzrqf_
#define LAPACK_dtzrzf dtzrzf_
#define LAPACK_dzsum1 dzsum1_
#define LAPACK_icmax1 icmax1_
#define LAPACK_ieeeck ieeeck_
#define LAPACK_ilaclc ilaclc_
#define LAPACK_ilaclr ilaclr_
#define LAPACK_iladiag iladiag_
#define LAPACK_iladlc iladlc_
#define LAPACK_iladlr iladlr_
#define LAPACK_ilaenv ilaenv_
#define LAPACK_ilaprec ilaprec_
#define LAPACK_ilaslc ilaslc_
#define LAPACK_ilaslr ilaslr_
#define LAPACK_ilatrans ilatrans_
#define LAPACK_ilauplo ilauplo_
#define LAPACK_ilaver ilaver_
#define LAPACK_ilazlc ilazlc_
#define LAPACK_ilazlr ilazlr_
#define LAPACK_iparmq iparmq_
#define LAPACK_izmax1 izmax1_
#define LAPACK_lsamen lsamen_
#define LAPACK_smaxloc smaxloc_
#define LAPACK_sbdsdc sbdsdc_
#define LAPACK_sbdsqr sbdsqr_
#define LAPACK_scsum1 scsum1_
#define LAPACK_sdisna sdisna_
#define LAPACK_sgbbrd sgbbrd_
#define LAPACK_sgbcon sgbcon_
#define LAPACK_sgbequ sgbequ_
#define LAPACK_sgbequb sgbequb_
#define LAPACK_sgbrfs sgbrfs_
#define LAPACK_sgbsv sgbsv_
#define LAPACK_sgbsvx sgbsvx_
#define LAPACK_sgbtf2 sgbtf2_
#define LAPACK_sgbtrf sgbtrf_
#define LAPACK_sgbtrs sgbtrs_
#define LAPACK_sgebak sgebak_
#define LAPACK_sgebal sgebal_
#define LAPACK_sgebd2 sgebd2_
#define LAPACK_sgebrd sgebrd_
#define LAPACK_sgecon sgecon_
#define LAPACK_sgeequ sgeequ_
#define LAPACK_sgeequb sgeequb_
#define LAPACK_sgees sgees_
#define LAPACK_sgeesx sgeesx_
#define LAPACK_sgeev sgeev_
#define LAPACK_sgeevx sgeevx_
#define LAPACK_sgegs sgegs_
#define LAPACK_sgegv sgegv_
#define LAPACK_sgehd2 sgehd2_
#define LAPACK_sgehrd sgehrd_
#define LAPACK_sgejsv sgejsv_
#define LAPACK_sgelq2 sgelq2_
#define LAPACK_sgelqf sgelqf_
#define LAPACK_sgels sgels_
#define LAPACK_sgelsd sgelsd_
#define LAPACK_sgelss sgelss_
#define LAPACK_sgelsx sgelsx_
#define LAPACK_sgelsy sgelsy_
#define LAPACK_sgeql2 sgeql2_
#define LAPACK_sgeqlf sgeqlf_
#define LAPACK_sgeqp3 sgeqp3_
#define LAPACK_sgeqpf sgeqpf_
#define LAPACK_sgeqr2 sgeqr2_
#define LAPACK_sgeqrf sgeqrf_
#define LAPACK_sgerfs sgerfs_
#define LAPACK_sgerq2 sgerq2_
#define LAPACK_sgerqf sgerqf_
#define LAPACK_sgesc2 sgesc2_
#define LAPACK_sgesdd sgesdd_
#define LAPACK_sgesv sgesv_
#define LAPACK_sgesvd sgesvd_
#define LAPACK_sgesvj sgesvj_
#define LAPACK_sgesvx sgesvx_
#define LAPACK_sgetc2 sgetc2_
#define LAPACK_sgetf2 sgetf2_
#define LAPACK_sgetrf sgetrf_
#define LAPACK_sgetri sgetri_
#define LAPACK_sgetrs sgetrs_
#define LAPACK_sggbak sggbak_
#define LAPACK_sggbal sggbal_
#define LAPACK_sgges sgges_
#define LAPACK_sggesx sggesx_
#define LAPACK_sggev sggev_
#define LAPACK_sggevx sggevx_
#define LAPACK_sggglm sggglm_
#define LAPACK_sgghrd sgghrd_
#define LAPACK_sgglse sgglse_
#define LAPACK_sggqrf sggqrf_
#define LAPACK_sggrqf sggrqf_
#define LAPACK_sggsvd sggsvd_
#define LAPACK_sggsvp sggsvp_
#define LAPACK_sgsvj0 sgsvj0_
#define LAPACK_sgsvj1 sgsvj1_
#define LAPACK_sgtcon sgtcon_
#define LAPACK_sgtrfs sgtrfs_
#define LAPACK_sgtsv sgtsv_
#define LAPACK_sgtsvx sgtsvx_
#define LAPACK_sgttrf sgttrf_
#define LAPACK_sgttrs sgttrs_
#define LAPACK_sgtts2 sgtts2_
#define LAPACK_shgeqz shgeqz_
#define LAPACK_shsein shsein_
#define LAPACK_shseqr shseqr_
#define LAPACK_sisnan sisnan_
#define LAPACK_slabad slabad_
#define LAPACK_slabrd slabrd_
#define LAPACK_slacn2 slacn2_
#define LAPACK_slacon slacon_
#define LAPACK_slacpy slacpy_
#define LAPACK_sladiv sladiv_
#define LAPACK_slae2 slae2_
#define LAPACK_slaebz slaebz_
#define LAPACK_slaed0 slaed0_
#define LAPACK_slaed1 slaed1_
#define LAPACK_slaed2 slaed2_
#define LAPACK_slaed3 slaed3_
#define LAPACK_slaed4 slaed4_
#define LAPACK_slaed5 slaed5_
#define LAPACK_slaed6 slaed6_
#define LAPACK_slaed7 slaed7_
#define LAPACK_slaed8 slaed8_
#define LAPACK_slaed9 slaed9_
#define LAPACK_slaeda slaeda_
#define LAPACK_slaein slaein_
#define LAPACK_slaev2 slaev2_
#define LAPACK_slaexc slaexc_
#define LAPACK_slag2 slag2_
#define LAPACK_slag2d slag2d_
#define LAPACK_slags2 slags2_
#define LAPACK_slagtf slagtf_
#define LAPACK_slagtm slagtm_
#define LAPACK_slagts slagts_
#define LAPACK_slagv2 slagv2_
#define LAPACK_slahqr slahqr_
#define LAPACK_slahr2 slahr2_
#define LAPACK_slahrd slahrd_
#define LAPACK_slaic1 slaic1_
#define LAPACK_slaisnan slaisnan_
#define LAPACK_slaln2 slaln2_
#define LAPACK_slals0 slals0_
#define LAPACK_slalsa slalsa_
#define LAPACK_slalsd slalsd_
#define LAPACK_slamrg slamrg_
#define LAPACK_slaneg slaneg_
#define LAPACK_slangb slangb_
#define LAPACK_slange slange_
#define LAPACK_slangt slangt_
#define LAPACK_slanhs slanhs_
#define LAPACK_slansb slansb_
#define LAPACK_slansf slansf_
#define LAPACK_slansp slansp_
#define LAPACK_slanst slanst_
#define LAPACK_slansy slansy_
#define LAPACK_slantb slantb_
#define LAPACK_slantp slantp_
#define LAPACK_slantr slantr_
#define LAPACK_slanv2 slanv2_
#define LAPACK_slapll slapll_
#define LAPACK_slapmt slapmt_
#define LAPACK_slapy2 slapy2_
#define LAPACK_slapy3 slapy3_
#define LAPACK_slaqgb slaqgb_
#define LAPACK_slaqge slaqge_
#define LAPACK_slaqp2 slaqp2_
#define LAPACK_slaqps slaqps_
#define LAPACK_slaqr0 slaqr0_
#define LAPACK_slaqr1 slaqr1_
#define LAPACK_slaqr2 slaqr2_
#define LAPACK_slaqr3 slaqr3_
#define LAPACK_slaqr4 slaqr4_
#define LAPACK_slaqr5 slaqr5_
#define LAPACK_slaqsb slaqsb_
#define LAPACK_slaqsp slaqsp_
#define LAPACK_slaqsy slaqsy_
#define LAPACK_slaqtr slaqtr_
#define LAPACK_slar1v slar1v_
#define LAPACK_slar2v slar2v_
#define LAPACK_slarf slarf_
#define LAPACK_slarfb slarfb_
#define LAPACK_slarfg slarfg_
#define LAPACK_slarfp slarfp_
#define LAPACK_slarft slarft_
#define LAPACK_slarfx slarfx_
#define LAPACK_slargv slargv_
#define LAPACK_slarnv slarnv_
#define LAPACK_slarra slarra_
#define LAPACK_slarrb slarrb_
#define LAPACK_slarrc slarrc_
#define LAPACK_slarrd slarrd_
#define LAPACK_slarre slarre_
#define LAPACK_slarrf slarrf_
#define LAPACK_slarrj slarrj_
#define LAPACK_slarrk slarrk_
#define LAPACK_slarrr slarrr_
#define LAPACK_slarrv slarrv_
#define LAPACK_slarscl2 slarscl2_
#define LAPACK_slartg slartg_
#define LAPACK_slartv slartv_
#define LAPACK_slaruv slaruv_
#define LAPACK_slarz slarz_
#define LAPACK_slarzb slarzb_
#define LAPACK_slarzt slarzt_
#define LAPACK_slas2 slas2_
#define LAPACK_slascl slascl_
#define LAPACK_slascl2 slascl2_
#define LAPACK_slasd0 slasd0_
#define LAPACK_slasd1 slasd1_
#define LAPACK_slasd2 slasd2_
#define LAPACK_slasd3 slasd3_
#define LAPACK_slasd4 slasd4_
#define LAPACK_slasd5 slasd5_
#define LAPACK_slasd6 slasd6_
#define LAPACK_slasd7 slasd7_
#define LAPACK_slasd8 slasd8_
#define LAPACK_slasda slasda_
#define LAPACK_slasdq slasdq_
#define LAPACK_slasdt slasdt_
#define LAPACK_slaset slaset_
#define LAPACK_slasq1 slasq1_
#define LAPACK_slasq2 slasq2_
#define LAPACK_slasq3 slasq3_
#define LAPACK_slasq4 slasq4_
#define LAPACK_slasq5 slasq5_
#define LAPACK_slasq6 slasq6_
#define LAPACK_slasr slasr_
#define LAPACK_slasrt slasrt_
#define LAPACK_slassq slassq_
#define LAPACK_slasv2 slasv2_
#define LAPACK_slaswp slaswp_
#define LAPACK_slasy2 slasy2_
#define LAPACK_slasyf slasyf_
#define LAPACK_slatbs slatbs_
#define LAPACK_slatdf slatdf_
#define LAPACK_slatps slatps_
#define LAPACK_slatrd slatrd_
#define LAPACK_slatrs slatrs_
#define LAPACK_slatrz slatrz_
#define LAPACK_slatzm slatzm_
#define LAPACK_slauu2 slauu2_
#define LAPACK_slauum slauum_
#define LAPACK_sopgtr sopgtr_
#define LAPACK_sopmtr sopmtr_
#define LAPACK_sorg2l sorg2l_
#define LAPACK_sorg2r sorg2r_
#define LAPACK_sorgbr sorgbr_
#define LAPACK_sorghr sorghr_
#define LAPACK_sorgl2 sorgl2_
#define LAPACK_sorglq sorglq_
#define LAPACK_sorgql sorgql_
#define LAPACK_sorgqr sorgqr_
#define LAPACK_sorgr2 sorgr2_
#define LAPACK_sorgrq sorgrq_
#define LAPACK_sorgtr sorgtr_
#define LAPACK_sorm2l sorm2l_
#define LAPACK_sorm2r sorm2r_
#define LAPACK_sormbr sormbr_
#define LAPACK_sormhr sormhr_
#define LAPACK_sorml2 sorml2_
#define LAPACK_sormlq sormlq_
#define LAPACK_sormql sormql_
#define LAPACK_sormqr sormqr_
#define LAPACK_sormr2 sormr2_
#define LAPACK_sormr3 sormr3_
#define LAPACK_sormrq sormrq_
#define LAPACK_sormrz sormrz_
#define LAPACK_sormtr sormtr_
#define LAPACK_spbcon spbcon_
#define LAPACK_spbequ spbequ_
#define LAPACK_spbrfs spbrfs_
#define LAPACK_spbstf spbstf_
#define LAPACK_spbsv spbsv_
#define LAPACK_spbsvx spbsvx_
#define LAPACK_spbtf2 spbtf2_
#define LAPACK_spbtrf spbtrf_
#define LAPACK_spbtrs spbtrs_
#define LAPACK_spftrf spftrf_
#define LAPACK_spftri spftri_
#define LAPACK_spftrs spftrs_
#define LAPACK_spocon spocon_
#define LAPACK_spoequ spoequ_
#define LAPACK_spoequb spoequb_
#define LAPACK_sporfs sporfs_
#define LAPACK_sposv sposv_
#define LAPACK_sposvx sposvx_
#define LAPACK_spotf2 spotf2_
#define LAPACK_spotrf spotrf_
#define LAPACK_spotri spotri_
#define LAPACK_spotrs spotrs_
#define LAPACK_sppcon sppcon_
#define LAPACK_sppequ sppequ_
#define LAPACK_spprfs spprfs_
#define LAPACK_sppsv sppsv_
#define LAPACK_sppsvx sppsvx_
#define LAPACK_spptrf spptrf_
#define LAPACK_spptri spptri_
#define LAPACK_spptrs spptrs_
#define LAPACK_spstf2 spstf2_
#define LAPACK_spstrf spstrf_
#define LAPACK_sptcon sptcon_
#define LAPACK_spteqr spteqr_
#define LAPACK_sptrfs sptrfs_
#define LAPACK_sptsv sptsv_
#define LAPACK_sptsvx sptsvx_
#define LAPACK_spttrf spttrf_
#define LAPACK_spttrs spttrs_
#define LAPACK_sptts2 sptts2_
#define LAPACK_srscl srscl_
#define LAPACK_ssbev ssbev_
#define LAPACK_ssbevd ssbevd_
#define LAPACK_ssbevx ssbevx_
#define LAPACK_ssbgst ssbgst_
#define LAPACK_ssbgv ssbgv_
#define LAPACK_ssbgvd ssbgvd_
#define LAPACK_ssbgvx ssbgvx_
#define LAPACK_ssbtrd ssbtrd_
#define LAPACK_ssfrk ssfrk_
#define LAPACK_sspcon sspcon_
#define LAPACK_sspev sspev_
#define LAPACK_sspevd sspevd_
#define LAPACK_sspevx sspevx_
#define LAPACK_sspgst sspgst_
#define LAPACK_sspgv sspgv_
#define LAPACK_sspgvd sspgvd_
#define LAPACK_sspgvx sspgvx_
#define LAPACK_ssprfs ssprfs_
#define LAPACK_sspsv sspsv_
#define LAPACK_sspsvx sspsvx_
#define LAPACK_ssptrd ssptrd_
#define LAPACK_ssptrf ssptrf_
#define LAPACK_ssptri ssptri_
#define LAPACK_ssptrs ssptrs_
#define LAPACK_sstebz sstebz_
#define LAPACK_sstedc sstedc_
#define LAPACK_sstegr sstegr_
#define LAPACK_sstein sstein_
#define LAPACK_sstemr sstemr_
#define LAPACK_ssteqr ssteqr_
#define LAPACK_ssterf ssterf_
#define LAPACK_sstev sstev_
#define LAPACK_sstevd sstevd_
#define LAPACK_sstevr sstevr_
#define LAPACK_sstevx sstevx_
#define LAPACK_ssycon ssycon_
#define LAPACK_ssyequb ssyequb_
#define LAPACK_ssyev ssyev_
#define LAPACK_ssyevd ssyevd_
#define LAPACK_ssyevr ssyevr_
#define LAPACK_ssyevx ssyevx_
#define LAPACK_ssygs2 ssygs2_
#define LAPACK_ssygst ssygst_
#define LAPACK_ssygv ssygv_
#define LAPACK_ssygvd ssygvd_
#define LAPACK_ssygvx ssygvx_
#define LAPACK_ssyrfs ssyrfs_
#define LAPACK_ssysv ssysv_
#define LAPACK_ssysvx ssysvx_
#define LAPACK_ssytd2 ssytd2_
#define LAPACK_ssytf2 ssytf2_
#define LAPACK_ssytrd ssytrd_
#define LAPACK_ssytrf ssytrf_
#define LAPACK_ssytri ssytri_
#define LAPACK_ssytrs ssytrs_
#define LAPACK_stbcon stbcon_
#define LAPACK_stbrfs stbrfs_
#define LAPACK_stbtrs stbtrs_
#define LAPACK_stfsm stfsm_
#define LAPACK_stftri stftri_
#define LAPACK_stfttp stfttp_
#define LAPACK_stfttr stfttr_
#define LAPACK_stgevc stgevc_
#define LAPACK_stgex2 stgex2_
#define LAPACK_stgexc stgexc_
#define LAPACK_stgsen stgsen_
#define LAPACK_stgsja stgsja_
#define LAPACK_stgsna stgsna_
#define LAPACK_stgsy2 stgsy2_
#define LAPACK_stgsyl stgsyl_
#define LAPACK_stpcon stpcon_
#define LAPACK_stprfs stprfs_
#define LAPACK_stptri stptri_
#define LAPACK_stptrs stptrs_
#define LAPACK_stpttf stpttf_
#define LAPACK_stpttr stpttr_
#define LAPACK_strcon strcon_
#define LAPACK_strevc strevc_
#define LAPACK_strexc strexc_
#define LAPACK_strrfs strrfs_
#define LAPACK_strsen strsen_
#define LAPACK_strsna strsna_
#define LAPACK_strsyl strsyl_
#define LAPACK_strti2 strti2_
#define LAPACK_strtri strtri_
#define LAPACK_strtrs strtrs_
#define LAPACK_strttf strttf_
#define LAPACK_strttp strttp_
#define LAPACK_stzrqf stzrqf_
#define LAPACK_stzrzf stzrzf_
#define LAPACK_zbdsqr zbdsqr_
#define LAPACK_zcgesv zcgesv_
#define LAPACK_zcposv zcposv_
#define LAPACK_zdrscl zdrscl_
#define LAPACK_zgbbrd zgbbrd_
#define LAPACK_zgbcon zgbcon_
#define LAPACK_zgbequ zgbequ_
#define LAPACK_zgbequb zgbequb_
#define LAPACK_zgbrfs zgbrfs_
#define LAPACK_zgbsv zgbsv_
#define LAPACK_zgbsvx zgbsvx_
#define LAPACK_zgbtf2 zgbtf2_
#define LAPACK_zgbtrf zgbtrf_
#define LAPACK_zgbtrs zgbtrs_
#define LAPACK_zgebak zgebak_
#define LAPACK_zgebal zgebal_
#define LAPACK_zgebd2 zgebd2_
#define LAPACK_zgebrd zgebrd_
#define LAPACK_zgecon zgecon_
#define LAPACK_zgeequ zgeequ_
#define LAPACK_zgeequb zgeequb_
#define LAPACK_zgees zgees_
#define LAPACK_zgeesx zgeesx_
#define LAPACK_zgeev zgeev_
#define LAPACK_zgeevx zgeevx_
#define LAPACK_zgegs zgegs_
#define LAPACK_zgegv zgegv_
#define LAPACK_zgehd2 zgehd2_
#define LAPACK_zgehrd zgehrd_
#define LAPACK_zgelq2 zgelq2_
#define LAPACK_zgelqf zgelqf_
#define LAPACK_zgels zgels_
#define LAPACK_zgelsd zgelsd_
#define LAPACK_zgelss zgelss_
#define LAPACK_zgelsx zgelsx_
#define LAPACK_zgelsy zgelsy_
#define LAPACK_zgeql2 zgeql2_
#define LAPACK_zgeqlf zgeqlf_
#define LAPACK_zgeqp3 zgeqp3_
#define LAPACK_zgeqpf zgeqpf_
#define LAPACK_zgeqr2 zgeqr2_
#define LAPACK_zgeqrf zgeqrf_
#define LAPACK_zgerfs zgerfs_
#define LAPACK_zgerq2 zgerq2_
#define LAPACK_zgerqf zgerqf_
#define LAPACK_zgesc2 zgesc2_
#define LAPACK_zgesdd zgesdd_
#define LAPACK_zgesv zgesv_
#define LAPACK_zgesvd zgesvd_
#define LAPACK_zgesvx zgesvx_
#define LAPACK_zgetc2 zgetc2_
#define LAPACK_zgetf2 zgetf2_
#define LAPACK_zgetrf zgetrf_
#define LAPACK_zgetri zgetri_
#define LAPACK_zgetrs zgetrs_
#define LAPACK_zggbak zggbak_
#define LAPACK_zggbal zggbal_
#define LAPACK_zgges zgges_
#define LAPACK_zggesx zggesx_
#define LAPACK_zggev zggev_
#define LAPACK_zggevx zggevx_
#define LAPACK_zggglm zggglm_
#define LAPACK_zgghrd zgghrd_
#define LAPACK_zgglse zgglse_
#define LAPACK_zggqrf zggqrf_
#define LAPACK_zggrqf zggrqf_
#define LAPACK_zggsvd zggsvd_
#define LAPACK_zggsvp zggsvp_
#define LAPACK_zgtcon zgtcon_
#define LAPACK_zgtrfs zgtrfs_
#define LAPACK_zgtsv zgtsv_
#define LAPACK_zgtsvx zgtsvx_
#define LAPACK_zgttrf zgttrf_
#define LAPACK_zgttrs zgttrs_
#define LAPACK_zgtts2 zgtts2_
#define LAPACK_zhbev zhbev_
#define LAPACK_zhbevd zhbevd_
#define LAPACK_zhbevx zhbevx_
#define LAPACK_zhbgst zhbgst_
#define LAPACK_zhbgv zhbgv_
#define LAPACK_zhbgvd zhbgvd_
#define LAPACK_zhbgvx zhbgvx_
#define LAPACK_zhbtrd zhbtrd_
#define LAPACK_zhecon zhecon_
#define LAPACK_zheequb zheequb_
#define LAPACK_zheev zheev_
#define LAPACK_zheevd zheevd_
#define LAPACK_zheevr zheevr_
#define LAPACK_zheevx zheevx_
#define LAPACK_zhegs2 zhegs2_
#define LAPACK_zhegst zhegst_
#define LAPACK_zhegv zhegv_
#define LAPACK_zhegvd zhegvd_
#define LAPACK_zhegvx zhegvx_
#define LAPACK_zherfs zherfs_
#define LAPACK_zhesv zhesv_
#define LAPACK_zhesvx zhesvx_
#define LAPACK_zhetd2 zhetd2_
#define LAPACK_zhetf2 zhetf2_
#define LAPACK_zhetrd zhetrd_
#define LAPACK_zhetrf zhetrf_
#define LAPACK_zhetri zhetri_
#define LAPACK_zhetrs zhetrs_
#define LAPACK_zhfrk zhfrk_
#define LAPACK_zhgeqz zhgeqz_
#define LAPACK_zhpcon zhpcon_
#define LAPACK_zhpev zhpev_
#define LAPACK_zhpevd zhpevd_
#define LAPACK_zhpevx zhpevx_
#define LAPACK_zhpgst zhpgst_
#define LAPACK_zhpgv zhpgv_
#define LAPACK_zhpgvd zhpgvd_
#define LAPACK_zhpgvx zhpgvx_
#define LAPACK_zhprfs zhprfs_
#define LAPACK_zhpsv zhpsv_
#define LAPACK_zhpsvx zhpsvx_
#define LAPACK_zhptrd zhptrd_
#define LAPACK_zhptrf zhptrf_
#define LAPACK_zhptri zhptri_
#define LAPACK_zhptrs zhptrs_
#define LAPACK_zhsein zhsein_
#define LAPACK_zhseqr zhseqr_
#define LAPACK_zlabrd zlabrd_
#define LAPACK_zlacgv zlacgv_
#define LAPACK_zlacn2 zlacn2_
#define LAPACK_zlacon zlacon_
#define LAPACK_zlacp2 zlacp2_
#define LAPACK_zlacpy zlacpy_
#define LAPACK_zlacrm zlacrm_
#define LAPACK_zlacrt zlacrt_
#define LAPACK_zladiv zladiv_
#define LAPACK_zlaed0 zlaed0_
#define LAPACK_zlaed7 zlaed7_
#define LAPACK_zlaed8 zlaed8_
#define LAPACK_zlaein zlaein_
#define LAPACK_zlaesy zlaesy_
#define LAPACK_zlaev2 zlaev2_
#define LAPACK_zlag2c zlag2c_
#define LAPACK_zlags2 zlags2_
#define LAPACK_zlagtm zlagtm_
#define LAPACK_zlahef zlahef_
#define LAPACK_zlahqr zlahqr_
#define LAPACK_zlahr2 zlahr2_
#define LAPACK_zlahrd zlahrd_
#define LAPACK_zlaic1 zlaic1_
#define LAPACK_zlals0 zlals0_
#define LAPACK_zlalsa zlalsa_
#define LAPACK_zlalsd zlalsd_
#define LAPACK_zlangb zlangb_
#define LAPACK_zlange zlange_
#define LAPACK_zlangt zlangt_
#define LAPACK_zlanhb zlanhb_
#define LAPACK_zlanhe zlanhe_
#define LAPACK_zlanhf zlanhf_
#define LAPACK_zlanhp zlanhp_
#define LAPACK_zlanhs zlanhs_
#define LAPACK_zlanht zlanht_
#define LAPACK_zlansb zlansb_
#define LAPACK_zlansp zlansp_
#define LAPACK_zlansy zlansy_
#define LAPACK_zlantb zlantb_
#define LAPACK_zlantp zlantp_
#define LAPACK_zlantr zlantr_
#define LAPACK_zlapll zlapll_
#define LAPACK_zlapmt zlapmt_
#define LAPACK_zlaqgb zlaqgb_
#define LAPACK_zlaqge zlaqge_
#define LAPACK_zlaqhb zlaqhb_
#define LAPACK_zlaqhe zlaqhe_
#define LAPACK_zlaqhp zlaqhp_
#define LAPACK_zlaqp2 zlaqp2_
#define LAPACK_zlaqps zlaqps_
#define LAPACK_zlaqr0 zlaqr0_
#define LAPACK_zlaqr1 zlaqr1_
#define LAPACK_zlaqr2 zlaqr2_
#define LAPACK_zlaqr3 zlaqr3_
#define LAPACK_zlaqr4 zlaqr4_
#define LAPACK_zlaqr5 zlaqr5_
#define LAPACK_zlaqsb zlaqsb_
#define LAPACK_zlaqsp zlaqsp_
#define LAPACK_zlaqsy zlaqsy_
#define LAPACK_zlar1v zlar1v_
#define LAPACK_zlar2v zlar2v_
#define LAPACK_zlarcm zlarcm_
#define LAPACK_zlarf zlarf_
#define LAPACK_zlarfb zlarfb_
#define LAPACK_zlarfg zlarfg_
#define LAPACK_zlarfp zlarfp_
#define LAPACK_zlarft zlarft_
#define LAPACK_zlarfx zlarfx_
#define LAPACK_zlargv zlargv_
#define LAPACK_zlarnv zlarnv_
#define LAPACK_zlarrv zlarrv_
#define LAPACK_zlarscl2 zlarscl2_
#define LAPACK_zlartg zlartg_
#define LAPACK_zlartv zlartv_
#define LAPACK_zlarz zlarz_
#define LAPACK_zlarzb zlarzb_
#define LAPACK_zlarzt zlarzt_
#define LAPACK_zlascl zlascl_
#define LAPACK_zlascl2 zlascl2_
#define LAPACK_zlaset zlaset_
#define LAPACK_zlasr zlasr_
#define LAPACK_zlassq zlassq_
#define LAPACK_zlaswp zlaswp_
#define LAPACK_zlasyf zlasyf_
#define LAPACK_zlat2c zlat2c_
#define LAPACK_zlatbs zlatbs_
#define LAPACK_zlatdf zlatdf_
#define LAPACK_zlatps zlatps_
#define LAPACK_zlatrd zlatrd_
#define LAPACK_zlatrs zlatrs_
#define LAPACK_zlatrz zlatrz_
#define LAPACK_zlatzm zlatzm_
#define LAPACK_zlauu2 zlauu2_
#define LAPACK_zlauum zlauum_
#define LAPACK_zpbcon zpbcon_
#define LAPACK_zpbequ zpbequ_
#define LAPACK_zpbrfs zpbrfs_
#define LAPACK_zpbstf zpbstf_
#define LAPACK_zpbsv zpbsv_
#define LAPACK_zpbsvx zpbsvx_
#define LAPACK_zpbtf2 zpbtf2_
#define LAPACK_zpbtrf zpbtrf_
#define LAPACK_zpbtrs zpbtrs_
#define LAPACK_zpftrf zpftrf_
#define LAPACK_zpftri zpftri_
#define LAPACK_zpftrs zpftrs_
#define LAPACK_zpocon zpocon_
#define LAPACK_zpoequ zpoequ_
#define LAPACK_zpoequb zpoequb_
#define LAPACK_zporfs zporfs_
#define LAPACK_zposv zposv_
#define LAPACK_zposvx zposvx_
#define LAPACK_zpotf2 zpotf2_
#define LAPACK_zpotrf zpotrf_
#define LAPACK_zpotri zpotri_
#define LAPACK_zpotrs zpotrs_
#define LAPACK_zppcon zppcon_
#define LAPACK_zppequ zppequ_
#define LAPACK_zpprfs zpprfs_
#define LAPACK_zppsv zppsv_
#define LAPACK_zppsvx zppsvx_
#define LAPACK_zpptrf zpptrf_
#define LAPACK_zpptri zpptri_
#define LAPACK_zpptrs zpptrs_
#define LAPACK_zpstf2 zpstf2_
#define LAPACK_zpstrf zpstrf_
#define LAPACK_zptcon zptcon_
#define LAPACK_zpteqr zpteqr_
#define LAPACK_zptrfs zptrfs_
#define LAPACK_zptsv zptsv_
#define LAPACK_zptsvx zptsvx_
#define LAPACK_zpttrf zpttrf_
#define LAPACK_zpttrs zpttrs_
#define LAPACK_zptts2 zptts2_
#define LAPACK_zrot zrot_
#define LAPACK_zspcon zspcon_
#define LAPACK_zspmv zspmv_
#define LAPACK_zspr zspr_
#define LAPACK_zsprfs zsprfs_
#define LAPACK_zspsv zspsv_
#define LAPACK_zspsvx zspsvx_
#define LAPACK_zsptrf zsptrf_
#define LAPACK_zsptri zsptri_
#define LAPACK_zsptrs zsptrs_
#define LAPACK_zstedc zstedc_
#define LAPACK_zstegr zstegr_
#define LAPACK_zstein zstein_
#define LAPACK_zstemr zstemr_
#define LAPACK_zsteqr zsteqr_
#define LAPACK_zsycon zsycon_
#define LAPACK_zsyequb zsyequb_
#define LAPACK_zsymv zsymv_
#define LAPACK_zsyr zsyr_
#define LAPACK_zsyrfs zsyrfs_
#define LAPACK_zsysv zsysv_
#define LAPACK_zsysvx zsysvx_
#define LAPACK_zsytf2 zsytf2_
#define LAPACK_zsytrf zsytrf_
#define LAPACK_zsytri zsytri_
#define LAPACK_zsytrs zsytrs_
#define LAPACK_ztbcon ztbcon_
#define LAPACK_ztbrfs ztbrfs_
#define LAPACK_ztbtrs ztbtrs_
#define LAPACK_ztfsm ztfsm_
#define LAPACK_ztftri ztftri_
#define LAPACK_ztfttp ztfttp_
#define LAPACK_ztfttr ztfttr_
#define LAPACK_ztgevc ztgevc_
#define LAPACK_ztgex2 ztgex2_
#define LAPACK_ztgexc ztgexc_
#define LAPACK_ztgsen ztgsen_
#define LAPACK_ztgsja ztgsja_
#define LAPACK_ztgsna ztgsna_
#define LAPACK_ztgsy2 ztgsy2_
#define LAPACK_ztgsyl ztgsyl_
#define LAPACK_ztpcon ztpcon_
#define LAPACK_ztprfs ztprfs_
#define LAPACK_ztptri ztptri_
#define LAPACK_ztptrs ztptrs_
#define LAPACK_ztpttf ztpttf_
#define LAPACK_ztpttr ztpttr_
#define LAPACK_ztrcon ztrcon_
#define LAPACK_ztrevc ztrevc_
#define LAPACK_ztrexc ztrexc_
#define LAPACK_ztrrfs ztrrfs_
#define LAPACK_ztrsen ztrsen_
#define LAPACK_ztrsna ztrsna_
#define LAPACK_ztrsyl ztrsyl_
#define LAPACK_ztrti2 ztrti2_
#define LAPACK_ztrtri ztrtri_
#define LAPACK_ztrtrs ztrtrs_
#define LAPACK_ztrttf ztrttf_
#define LAPACK_ztrttp ztrttp_
#define LAPACK_ztzrqf ztzrqf_
#define LAPACK_ztzrzf ztzrzf_
#define LAPACK_zung2l zung2l_
#define LAPACK_zung2r zung2r_
#define LAPACK_zungbr zungbr_
#define LAPACK_zunghr zunghr_
#define LAPACK_zungl2 zungl2_
#define LAPACK_zunglq zunglq_
#define LAPACK_zungql zungql_
#define LAPACK_zungqr zungqr_
#define LAPACK_zungr2 zungr2_
#define LAPACK_zungrq zungrq_
#define LAPACK_zungtr zungtr_
#define LAPACK_zunm2l zunm2l_
#define LAPACK_zunm2r zunm2r_
#define LAPACK_zunmbr zunmbr_
#define LAPACK_zunmhr zunmhr_
#define LAPACK_zunml2 zunml2_
#define LAPACK_zunmlq zunmlq_
#define LAPACK_zunmql zunmql_
#define LAPACK_zunmqr zunmqr_
#define LAPACK_zunmr2 zunmr2_
#define LAPACK_zunmr3 zunmr3_
#define LAPACK_zunmrq zunmrq_
#define LAPACK_zunmrz zunmrz_
#define LAPACK_zunmtr zunmtr_
#define LAPACK_zupgtr zupgtr_
#define LAPACK_zupmtr zupmtr_
#define LAPACK_dlamc1 dlamc1_
#define LAPACK_ilaver ilaver_
#define LAPACK_slamch slamch_
#define LAPACK_slamc1 slamc1_
#define LAPACK_slamc2 slamc2_
#define LAPACK_slamc3 slamc3_
#define LAPACK_slamc4 slamc4_
#define LAPACK_slamc5 slamc5_
#define LAPACK_dlamch dlamch_
#define LAPACK_dlamc1 dlamc1_
#define LAPACK_dlamc2 dlamc2_
#define LAPACK_dlamc3 dlamc3_
#define LAPACK_dlamc4 dlamc4_
#define LAPACK_dlamc5 dlamc5_
#define LAPACK_ilaenv ilaenv_

#endif