/// \file clebsch_gordan.h
/// \brief Clebsch-Gordan coefficient tables.
///
/// 'j' quantum numbers are represented times 2, to support half-integers.
/// 'm' quantum numbers are enumerated as (j, j - 1, ..., -j).
///
/// This file has been generated by 'clebsch_gordan_gen.py'.

#include "qnumber.h"


// format: cg_j1_j2_j3[j1+1][j2+1][j3+1]
extern const double cg_0_0_0[1][1][1];
extern const double cg_0_1_1[1][2][2];
extern const double cg_0_2_2[1][3][3];
extern const double cg_0_3_3[1][4][4];
extern const double cg_0_4_4[1][5][5];
extern const double cg_0_5_5[1][6][6];
extern const double cg_1_0_1[2][1][2];
extern const double cg_1_1_0[2][2][1];
extern const double cg_1_1_2[2][2][3];
extern const double cg_1_2_1[2][3][2];
extern const double cg_1_2_3[2][3][4];
extern const double cg_1_3_2[2][4][3];
extern const double cg_1_3_4[2][4][5];
extern const double cg_1_4_3[2][5][4];
extern const double cg_1_4_5[2][5][6];
extern const double cg_1_5_4[2][6][5];
extern const double cg_1_5_6[2][6][7];
extern const double cg_2_0_2[3][1][3];
extern const double cg_2_1_1[3][2][2];
extern const double cg_2_1_3[3][2][4];
extern const double cg_2_2_0[3][3][1];
extern const double cg_2_2_2[3][3][3];
extern const double cg_2_2_4[3][3][5];
extern const double cg_2_3_1[3][4][2];
extern const double cg_2_3_3[3][4][4];
extern const double cg_2_3_5[3][4][6];
extern const double cg_2_4_2[3][5][3];
extern const double cg_2_4_4[3][5][5];
extern const double cg_2_4_6[3][5][7];
extern const double cg_2_5_3[3][6][4];
extern const double cg_2_5_5[3][6][6];
extern const double cg_2_5_7[3][6][8];
extern const double cg_3_0_3[4][1][4];
extern const double cg_3_1_2[4][2][3];
extern const double cg_3_1_4[4][2][5];
extern const double cg_3_2_1[4][3][2];
extern const double cg_3_2_3[4][3][4];
extern const double cg_3_2_5[4][3][6];
extern const double cg_3_3_0[4][4][1];
extern const double cg_3_3_2[4][4][3];
extern const double cg_3_3_4[4][4][5];
extern const double cg_3_3_6[4][4][7];
extern const double cg_3_4_1[4][5][2];
extern const double cg_3_4_3[4][5][4];
extern const double cg_3_4_5[4][5][6];
extern const double cg_3_4_7[4][5][8];
extern const double cg_3_5_2[4][6][3];
extern const double cg_3_5_4[4][6][5];
extern const double cg_3_5_6[4][6][7];
extern const double cg_3_5_8[4][6][9];
extern const double cg_4_0_4[5][1][5];
extern const double cg_4_1_3[5][2][4];
extern const double cg_4_1_5[5][2][6];
extern const double cg_4_2_2[5][3][3];
extern const double cg_4_2_4[5][3][5];
extern const double cg_4_2_6[5][3][7];
extern const double cg_4_3_1[5][4][2];
extern const double cg_4_3_3[5][4][4];
extern const double cg_4_3_5[5][4][6];
extern const double cg_4_3_7[5][4][8];
extern const double cg_4_4_0[5][5][1];
extern const double cg_4_4_2[5][5][3];
extern const double cg_4_4_4[5][5][5];
extern const double cg_4_4_6[5][5][7];
extern const double cg_4_4_8[5][5][9];
extern const double cg_4_5_1[5][6][2];
extern const double cg_4_5_3[5][6][4];
extern const double cg_4_5_5[5][6][6];
extern const double cg_4_5_7[5][6][8];
extern const double cg_4_5_9[5][6][10];
extern const double cg_5_0_5[6][1][6];
extern const double cg_5_1_4[6][2][5];
extern const double cg_5_1_6[6][2][7];
extern const double cg_5_2_3[6][3][4];
extern const double cg_5_2_5[6][3][6];
extern const double cg_5_2_7[6][3][8];
extern const double cg_5_3_2[6][4][3];
extern const double cg_5_3_4[6][4][5];
extern const double cg_5_3_6[6][4][7];
extern const double cg_5_3_8[6][4][9];
extern const double cg_5_4_1[6][5][2];
extern const double cg_5_4_3[6][5][4];
extern const double cg_5_4_5[6][5][6];
extern const double cg_5_4_7[6][5][8];
extern const double cg_5_4_9[6][5][10];
extern const double cg_5_5_0[6][6][1];
extern const double cg_5_5_2[6][6][3];
extern const double cg_5_5_4[6][6][5];
extern const double cg_5_5_6[6][6][7];
extern const double cg_5_5_8[6][6][9];
extern const double cg_5_5_10[6][6][11];

extern const double* cg_table[6][6][11];


double clebsch_gordan(const qnumber j1, const qnumber j2, const qnumber j3, const int im1, const int im2, const int im3);
