/// \file su2_recoupling.h
/// \brief SU(2) recoupling coefficient tables.
///
/// 'j' quantum numbers are represented times 2, to support half-integers.
///
/// This file has been generated by 'su2_recoupling_gen.py'.

#pragma once

#include "qnumber.h"


double su2_recoupling_coefficient(const qnumber ja, const qnumber jb, const qnumber jc, const qnumber js, const qnumber je, const qnumber jf);
